// Generated by AI App Builder — Agent 5.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not configured.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not configured.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not configured.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:735279769416:android:845f95d172117a3ccdb57d',
    messagingSenderId: '735279769416',
    projectId: 'streak-forge-567341',
    storageBucket: 'streak-forge-567341.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:735279769416:ios:9b4e66a86a84f3bfcdb57d',
    messagingSenderId: '735279769416',
    projectId: 'streak-forge-567341',
    storageBucket: 'streak-forge-567341.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.futurebuild.streakforge',
  );
}
