// Generated by AI App Builder — Agent 5.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not configured.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not configured.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not configured.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX71FGARQ16cCaZU7Q2kumv6gqQYrZL-M',
    appId: '1:494877238884:android:9299b8a990d2be72626171',
    messagingSenderId: '494877238884',
    projectId: 'streak-forge-569277',
    storageBucket: 'streak-forge-569277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX71FGARQ16cCaZU7Q2kumv6gqQYrZL-M',
    appId: '1:494877238884:ios:81275449d5e8dc52626171',
    messagingSenderId: '494877238884',
    projectId: 'streak-forge-569277',
    storageBucket: 'streak-forge-569277.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.futurebuild.streakforge',
  );
}
