// Generated by AI App Builder — Agent 5.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError('macOS is not configured.');
      case TargetPlatform.windows:
        throw UnsupportedError('Windows is not configured.');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux is not configured.');
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtJ4j5u8SMQovzvG9bH-5SAq3RBbujp68',
    appId: '1:36498065610:android:b1cb8613114387a3facc33',
    messagingSenderId: '36498065610',
    projectId: 'streak-forge-567485',
    storageBucket: 'streak-forge-567485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtJ4j5u8SMQovzvG9bH-5SAq3RBbujp68',
    appId: '1:36498065610:ios:b5ba907b91d79257facc33',
    messagingSenderId: '36498065610',
    projectId: 'streak-forge-567485',
    storageBucket: 'streak-forge-567485.appspot.com',
    iosClientId: '',
    iosBundleId: 'com.futurebuild.streakforge',
  );
}
